// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkusatttmfxzaittfcnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrdXNhdHR0bWZ4emFpdHRmY25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzY0NTcsImV4cCI6MjA2NTI1MjQ1N30.kYlFW-UML1zz-xfdX3x26UZLsukAiCLndJA_zlGL7MU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);