// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tahhdmbifzjlxrtntjaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhaGhkbWJpZnpqbHhydG50amF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDAwMDUsImV4cCI6MjA2NTY3NjAwNX0.rPmDeJKWEvWoNIP7SEwjdBocNiEGiSx7Y4ZNgdK-ke8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);